CMS_HOST: studio.local.overhang.io
CONTACT_EMAIL: contact@local.overhang.io
ENABLE_HTTPS: false
ID: WgXrWIHQN3GNq0215Rpi7xwp
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEowIBAAKCAQEAnLq5gTit7sUA+/TiFCGWpiNM6qGRNDHd36kaw/NdYb440FVP

  jMMW1XOuTQEYgAXZGO5lDy0uw354czdBYYWfYLfMkwuN81Ff6kYdpC8MSy5/wS15

  KwxKZKjN4kIRtF0hCT4qO0xw/DyiIL48N0YFMNXdmQemCz+6LSG+IdoZnBjY0tNi

  s6oycZkvC8gxWxSPb4bIi3BT6wKN25yTW+GI+69KKp1OLMc36T9+y7T4MtESZFu7

  U2ZyYEzdk7jGVqPWedJw83la7Kff1LsCuagYoI8M8DV+3l2lW8q0mz+Gg7+Eeztg

  GiWqs9aqQTy61zi0wM25TxuYG9cDYHT9oJL8cQIDAQABAoIBAAEBmHQE2rLwvbvg

  YV8zecPFI3MUv6t3rV+DUGLgoxNI5QC5aZJqTcCLt0570TJ9s0fhLRCGPUwuVc4d

  pJTllblyj4YJW9/Uezyk5OrxsZVun9VaMS/1hq6Bj71O0R97cRqn96NIyPRG5pRf

  KCNA8xI41ZsurDqYlGz6eQA6POudMJFUcQK3AWTjEYGPFTFvhLFlZZWgEtxXVz0o

  qo3lWxK8RF0yjgNJfpoGpmcMeet5Onr5auR4+z4ghMiE//BBFeGmvzbjbX/4MU2H

  8uYCMr/uhiYKkD/0w4twE7yX8mGMJA0MdeqZc9PwaV/k7TyJCIlVG6SgHWQtbpNS

  dqOzqh0CgYEAvL2GJjXb+afC8CQt1AHmDHSjbM9nPe0vKSnLxrmFqLWBgrI1NxPI

  tT/uktxcUISufoLnUQLiXRWjlIX6/mLMsr+qpKm/hD3ySQQPh5puRG85YNdXk0jq

  WGezZesV5FzXX34FAOiEdwu4MUZxWyhUGBmNldUaWllpIZNJP9tkEmcCgYEA1JTl

  A1/7qmK1LRLOyoyP5xsBxFhwE3nMDkMj8DzhSRYgHURyseEZl5EFUFZwLv/qC/UV

  b7YNo2bkKYnYd7rBeFxX/maKHv02bvL0FZcGvyjYScwQfFDP3ZY112TvYuRFbcmG

  ocR5JqQ/8I426X1fo9qAWrBZuFZJQl+6efCoo2cCgYAxDyZuijNqmmO+XfkXkYLF

  nA/aubKBU0Sd84JHXnPSnZNTcJUKgvb5vet6exL3zvU4ZzhPQ2upfHVvpr/OHcpN

  cCqf8IuaiSuQNSEAQ3EEEtEcTf0yiJJ5dkMYa9nd6RAGf1A3ozjDZOV00XWnlzz8

  oq+90Y2vDGyaUJmKorFJYwKBgEytdDmWanlX50/dw9dNgi5zEF0ZJTvxJ8hRMWpb

  G0u4flbwNIqyzf9coNUMiKR7TJmJinTj7uFsoInXHcx6AYT/kgHCTLnGzdaRLbeH

  5TgYbIOZ5qxgncmof700vCAohF6IXVaGPsjQX/vN4EKyJUg97SRJDeOuw/f7/ZA0

  XS+rAoGBAKZBp80VEhcwORJ86iXdZz0m3b743r9E5FUBWAK0HZAKxIxGAFe0vt8W

  N8BQeZicmbSDawV9l1dp/+NQYRgr8tD+C6sxk2EjIbsG4kpygJ5cfy42vRd5CiuL

  QjYFoBuX0Ph+Oh/bTiu9k2f6PGfeKcEMSA5ZsVkBz+iI9wt5TK2/

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
MYSQL_ROOT_PASSWORD: rAxo673e
OPENEDX_MYSQL_PASSWORD: w0Rt9u1A
OPENEDX_SECRET_KEY: obGIZYddbmZDxVoYJvk8KvDw
PLATFORM_NAME: My Open edX
